sudo: required

services: docker

branches:
  # ignore:
  #   - /test-.*/
  only:
    - master

before_install:
  - docker pull matthewfeickert/latex-docker:latest
  - sudo apt-get -qq update
  - sudo apt-get install -y sshpass

jobs:
  include:
    - stage: Build Thesis
      script:
        # Compile thesis
        - git submodule update --init --recursive
        - docker run --user='root' --rm -v $PWD:/home/docker matthewfeickert/latex-docker /bin/bash -c "make final"
        - mv feickert_thesis.pdf draft.pdf
        # Deploy thesis
        - echo -e "Host *\n\tStrictHostKeyChecking no" >> ~/.ssh/config
        - SSHPASS=$LXPLUS_PASS sshpass -e scp draft.pdf feickert@lxplus.cern.ch:/eos/user/f/feickert/www/ATLAS/thesis/draft.pdf
        - SSHPASS=$LXPLUS_PASS sshpass -e scp abstract.pdf feickert@lxplus.cern.ch:/eos/user/f/feickert/www/ATLAS/thesis/abstract.pdf
        - SSHPASS=$PHYSSERVER_PASS sshpass -e scp draft.pdf mfeickert@rubin.physics.smu.edu:/users/mfeickert/public_html/thesis/draft.pdf
        - SSHPASS=$PHYSSERVER_PASS sshpass -e scp abstract.pdf mfeickert@rubin.physics.smu.edu:/users/mfeickert/public_html/thesis/abstract.pdf

notifications:
  # email:
  #   recipients:
  #     - matthew.feickert@cern.ch
  #   on_success: never
  #   on_failure: always

  email:
    recipients:
      - matthew.feickert@cern.ch
      # - ssekula@smu.edu
    on_success: always
    on_failure: never
