version: 2
jobs:
  build:
    docker:
      - image: matthewfeickert/feickert-thesis
    steps:
      - checkout
      - run:
          name: Print current datetime
          command: date -u '+%Y-%m-%d %H:%M:%S'
      - run:
          name: Compile Thesis
          command: |
            make final
            ls -la
      - deploy:
          name: Push draft to ATLAS internal public web area
          command: SSHPASS="${LXPLUS_PASS}" sshpass -e scp draft_*.pdf feickert@lxplus.cern.ch:/eos/user/f/feickert/www/thesis/draft.pdf
