version: 2
jobs:
  build:
    docker:
      - image: matthewfeickert/feickert-thesis
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo "This is Matthew's Thesis"
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: List the Environment
          command: ls -la
      - run:
          name: Compile Thesis
          command: make final && ls -la
