version: 2
jobs:
  build:
    docker:
      - image: matthewfeickert/latex-docker
    branches:
      ignore:
        - /test-.*/
    steps:
      - checkout
      - run:
          name: Print current datetime
          command: date -u '+%Y-%m-%d %H:%M:%S'
      - run:
          name: Compile Thesis
          command: |
            git submodule update --init --recursive
            make final
            echo ""
            ls -la
      - deploy:
       # For Docker builds disable host key checking. Be aware that by adding
       # that you are suspectible to man-in-the-middle attacks.
       # Apply the ssh config to all host servers instead of applying to each
       # host name. (example host names: lxplus.cern.ch, rubin.physics.smu.edu)
          name: Push draft and abstract to ATLAS and SMU internal public web areas
          command: |
              echo -e "Host *\n\tStrictHostKeyChecking no" >> ~/.ssh/config
              if [[ ! -z $CIRCLE_PULL_REQUEST ]]; then
                SSHPASS=$LXPLUS_PASS sshpass -e scp feickert_thesis.pdf feickert@lxplus.cern.ch:/eos/user/f/feickert/www/ATLAS/thesis/PRs/draft_PR${CIRCLE_PULL_REQUEST##*/}.pdf
                echo "### File viewable at: https://cern.ch/feickert/ATLAS/thesis/PRs/draft_PR${CIRCLE_PULL_REQUEST##*/}.pdf"
                SSHPASS=$PHYSSERVER_PASS sshpass -e scp feickert_thesis.pdf mfeickert@rubin.physics.smu.edu:/users/mfeickert/public_html/thesis/PRs/draft_PR${CIRCLE_PULL_REQUEST##*/}.pdf
                echo "### File viewable at: https://www.physics.smu.edu/mfeickert/thesis/PRs/draft_PR${CIRCLE_PULL_REQUEST##*/}.pdf"
              elif [[ "$CIRCLE_BRANCH" == "master" ]]; then
                SSHPASS=$LXPLUS_PASS sshpass -e scp feickert_thesis.pdf feickert@lxplus.cern.ch:/eos/user/f/feickert/www/ATLAS/thesis/draft.pdf
                SSHPASS=$LXPLUS_PASS sshpass -e scp feickert_thesis.pdf feickert@lxplus.cern.ch:/eos/user/f/feickert/www/feickert-thesis.pdf
                SSHPASS=$LXPLUS_PASS sshpass -e scp abstract.pdf feickert@lxplus.cern.ch:/eos/user/f/feickert/www/ATLAS/thesis/abstract.pdf
                echo "### File viewable at: https://cern.ch/feickert/ATLAS/thesis/draft.pdf"
                SSHPASS=$PHYSSERVER_PASS sshpass -e scp feickert_thesis.pdf mfeickert@rubin.physics.smu.edu:/users/mfeickert/public_html/thesis/draft.pdf
                SSHPASS=$PHYSSERVER_PASS sshpass -e scp abstract.pdf mfeickert@rubin.physics.smu.edu:/users/mfeickert/public_html/thesis/abstract.pdf
                echo "### File viewable at: https://www.physics.smu.edu/mfeickert/thesis/draft.pdf"
              fi
